name: star-sync

services:
    ss-server:
        image: ghcr.io/star-sync/ss-server:${SS_SERVER_VERSION}
        ports:
            - "${SS_SERVER_PORT}:8080"
        env_file: ".env"
        networks:
            - star-sync

    ss-web:
        image: ghcr.io/star-sync/ss-web:${SS_WEB_VERSION}
        ports:
            - "${SS_WEB_PORT}:5000"
        env_file: ".env"
        networks:
            - star-sync

    ss-db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${SS_DB_USER}
            POSTGRES_PASSWORD: ${SS_DB_PASSWORD}
            POSTGRES_DB: ${SS_DB_NAME}
        ports:
            - "${SS_DB_PORT}:5432"
        networks:
            - star-sync
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/initdb:/docker-entrypoint-initdb.d

networks:
    star-sync:

volumes:
    db-data:
        driver: local
