name: star-sync

services:
    ss-core:
        image: ghcr.io/star-sync/ss-core:${SS_CORE_VERSION}
        ports:
            - "${SS_CORE_PORT}:${SS_CORE_INTERNAL_PORT}"
        env_file: ".env"
        networks:
            - star-sync

    ss-web:
        image: ghcr.io/star-sync/ss-web:${SS_WEB_VERSION}
        ports:
            - "${SS_WEB_PORT}:${SS_WEB_INTERNAL_PORT}"
        env_file: ".env"
        networks:
            - star-sync

    ss-db:
        image: postgres:latest
        env_file: ".env"
        ports:
            - "${POSTGRES_PORT}:5432"
        networks:
            - star-sync
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/initdb:/docker-entrypoint-initdb.d

networks:
    # we have to switch this to external as we create the network
    # in the Makefile, therefore its not created in the stack, and is "external"
    star-sync:
        name: star-sync_star-sync
        driver: bridge
        external: true

volumes:
    db-data:
        driver: local
